centreon/centreon-gorgone

packaging/centreon-gorgone.spectemplate
Set 775 permissions on config.d directory and add apache user to centreon-gorgone group.
=> Set 775 permissions on config.d directory

.gitignore, LICENSE.txt, install.sh, sourceInstall/functions, sourceInstall/vars
Add an installation from sources script
=> enh(core): gorgone add a source install script

packaging/centreon-gorgone.spectemplate
See centreon/centreon-build#241
=> Move centreon-gorgone user and group modification to other packages

install.sh
I add mode silent. example
install.sh -i -f gorgone.tmpl
fichier tmpl for Debian
```
GORGONE_LOG="/var/log/centreon-gorgone"
GORGONE_VARLIB="/var/lib/centreon-gorgone"
GORGONE_ETC="/etc/centreon-gorgone"
GORGONE_CONF_FILE="/config.yaml"
GORGONE_BINDIR="/usr/bin/"
GORGONE_PERL="/usr/share/perl5/"
INIT_D="/etc/init.d"
CRON_D="/etc/cron.d"
LOGROTATE_D="/etc/logrotate.d"
SYSTEM_D="/etc/systemd/system"
SYSCONFIG="/etc/default"
GORGONE_USER="centreon-gorgone"
GORGONE_GROUP="centreon-gorgone"
```
=> modifiy install for mode silent

packaging/centreon-gorgone.spectemplate
Closes https://github.com/centreon/centreon-gorgone/issues/40
Refs MON-5959
=> enh(packaging): add minimal version for perl(Libssh::Session)

Jenkinsfile, packaging/centreon-gorgone.spectemplate, sonar-project.properties
Preparing the version 21.04.0 for module centreon-gorgone
=> chore(install): update version to 21.04.0

packaging/centreon-gorgone.spectemplate
set version to 20.04.7 in files
=> chore(install): upgrade to version 20.04.7

packaging/centreon-gorgone.spectemplate
Update version to 20.10.1 in files
=> chore(install): update to version 20.10.1

packaging/centreon-gorgone.spectemplate
Update version to 20.04.8 in files
=> chore(install): update to version 20.04.8

gorgone/modules/centreon/anomalydetection/class.pm
This PR change the AD default sync threshold to 8 hours instead of 24.
=> fix(anomalydetection): change AD sync threshold value

packaging/centreon-gorgone.spectemplate
=> chore(install): update to version 20.10.2

packaging/centreon-gorgone.spectemplate
=> chore(install): update to version 20.04.9

gorgone/class/clientzmq.pm, gorgone/modules/core/proxy/class.pm, gorgone/modules/core/proxy/hooks.pm
Avoid proxy pool blocking in case of unreachable nodes.
=> Proxy internal communication

docs/modules/centreon/autodiscovery.md
"filter_rules" and not ""filters_rules" (line 281)
=> Fix documentation

packaging/centreon-gorgone.spectemplate
Update version to 20.10.3 in files.
=> chore(install): update version to 20.10.3

packaging/centreon-gorgone.spectemplate
Update version to 20.04.10 in files.
=> chore(install): update version to 20.04.10

packaging/centreon-gorgone.spectemplate
=> chore(version): upgrade to 21.04.0

Jenkinsfile, packaging/centreon-gorgone.spectemplate
=> chore(version): prepare 21.10 serie

packaging/centreon-gorgone.spectemplate
Update version to 20.04.11 in files.
=> chore(install): update to version 20.04.11

packaging/centreon-gorgone.spectemplate
Update version to 21.04.1 in files.
=> chore(install): update to version 21.04.1

packaging/centreon-gorgone.spectemplate
Update version to 20.10.4 in files.
=> chore(install): update version to 20.10.4

install.sh
logrotate doesn't work with 755 rights on config file
=> change gorgoned logrotate config file rights

Jenkinsfile
Fixing the issue with quality gate timeout from sonarqube by querying sonarqube api directly and check the success status.
<h2> How this pull request can be tested ? </h2>
Launch pipeline on that PR
=> fix(ci): manage Quality Gate timeout

packaging/centreon-gorgone.spectemplate
Update version to 20.10.5 in files.
=> chore(install): update version to 20.10.5

packaging/centreon-gorgone.spectemplate
Update version to 21.04.2 in files.
=> chore(install): update version to 21.04.2

Jenkinsfile
In order to push rpm directly to yum.centreon.com, here's the new jenkinsfile.
=> enh(ci): new pipeline workflow

packaging/centreon-gorgone.spectemplate
Update version to 21.04.3 in files
=> chore(install): update version to 21.04.03

packaging/centreon-gorgone.spectemplate
Update version to 20.10.6 in files.
=> chore(install): update version to 20.10.6

packaging/centreon-gorgone.spectemplate
=> chore(install): update to version to 21.10.1

packaging/centreon-gorgone.spectemplate
=> chore(install): update version to 21.04.4

gorgone/class/tpapi/clapi.pm, gorgone/modules/centreon/legacycmd/class.pm
Target : 22.04.x
Refs: MON-6463
=> enh(clapi): use clapi password from configuration

packaging/centreon-gorgone.spectemplate
Update version to 21.04.5 in files.
=> chore(install): update version to 21.04.5

packaging/centreon-gorgone.spectemplate
Update version to 21.10.2 in files.
=> chore(install): update version to 21.10.2

install/src/centreon-api.yaml, packaging/centreon-api.yaml
This updates Centreon API password
=> fix(config): Update Centreon API password

Jenkinsfile
enable el8 build and packaging 21.10.x
=> enable el8 build and packaging 21.10.x

Jenkinsfile
enable el8 build and packaging dev 20.10.x
=> enable el8 build and packaging dev 20.10.x

Jenkinsfile
enable el8 build and packaging dev 21.04.x
=> enable el8 build and packaging dev 21.04.x

packaging/centreon-gorgone.spectemplate
=> fix(packaging): fix rights on configuration files

packaging/centreon-gorgone.spectemplate
Update version to 20.10.7 in files.
=> chore(install): update version to 20.10.7

Jenkinsfile, ci/Jenkinsfile, packaging/centreon-gorgone.spectemplate
=> core(version): prepare the 22.10 version

ci/scripts/gorgone-deb-package.sh
Add apt update to make sure the package cache is up to date.
<h2> How this pull request can be tested ? </h2>
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.
=> fix(ci): update gorgone-deb-package.sh
